openapi: 3.0.4
info:
  version: 1.0.12
  title: Event Horizon Timer
paths:
  /api/timers:
    post:
      summary: create a new timer
      description: |-
        create a new timer
      responses:
        '200':
          description: success.
  /api/timers/${id}:
    get:
      summary: get a timer
      description: |-
        get a timer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  timer:
                    description: timer
                    type: object
                    properties:
                      id:
                        description: id
                        type: string
                        format: uuid
                      status:
                        description: status
                        type: string
                        enum: [running, stopped]
                      target_time:
                        description: target time
                        type: number
                      duration:
                        description: duration
                        type: integer
    put:
      summary: update a timer
      description: |-
        update a timer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: success.
