openapi: 3.0.4
info:
  version: 1.0.12
  title: Event Horizon Timer
  description: |-
    event horizon timer
paths:
  /:
    get:
      summary: root
      responses:
       '200':
         description: root
  /api/timers:
    post:
      summary: create a new timer
      responses:
        '200':
          description: success.
