openapi: 3.0.4
info:
  version: 1.0.12
  title: Event Horizon Timer
tags:
  - name: timer
    description: timer
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: hex
paths:
  /api/timers:
    post:
      summary: create a new timer
      description: |-
        create a new timer
      tags:
        - timer
      responses:
        '201':
          description: success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  timer:
                    description: timer
                    type: object
                    properties:
                      id:
                        description: id
                        type: string
                        format: uuid
                        example: 3f4d7fca-4a06-4af7-8da4-90445e52de17
                      token:
                        description: token
                        type: string
                        format: hex
                        example: "112c414625408e15974642192ca630ba854880ff761053cdd0df6483dcd531cf"
                      status:
                        description: status
                        type: string
                        example: stopped
                      target_time:
                        description: target time
                        type: number
                        example: 1757817633
                      duration:
                        description: duration
                        type: integer
                        example: 0
  /api/timers/{id}:
    get:
      summary: get a timer
      description: |-
        get a timer
      tags:
        - timer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  timer:
                    description: timer
                    type: object
                    properties:
                      id:
                        description: id
                        type: string
                        format: uuid
                        example: 3f4d7fca-4a06-4af7-8da4-90445e52de17
                      status:
                        description: status
                        type: string
                        enum: [running, stopped]
                      target_time:
                        description: target time
                        type: number
                        example: 1757817633
                      duration:
                        description: duration
                        type: integer
                        example: 180
    put:
      summary: update a timer
      description: |-
        update a timer
      tags:
        - timer
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - status
                - target_time
                - duration
              properties:
                status:
                  description: timer status
                  type: string
                  enum: [running, stopped]
                  example: "running"
                target_time:
                  description: target time
                  type: number
                  minimum: 0
                  example: 1757817633
                duration:
                  description: duration
                  type: integer
                  minimum: 0
                  example: 180
      responses:
        '200':
          description: success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  timer:
                    description: timer
                    type: object
                    properties:
                      id:
                        description: id
                        type: string
                        format: uuid
                        example: 3f4d7fca-4a06-4af7-8da4-90445e52de17
                      status:
                        description: status
                        type: string
                        enum: [running, stopped]
                      target_time:
                        description: target time
                        type: number
                        example: 1757817633
                      duration:
                        description: duration
                        type: integer
                        example: 180
